### ISSUE TITLE
Server error caused by bad session cookie

### ISSUE THREAD

**Issue by andy128k** [edicl/hunchentoot#101]
Session cookie without #\\: causes server to respond 500 instead of discarding. This blocks visitor from receiving new valid cookie.

**Comment by hanshuebner** [comment]
Can you provide a way to test the erroneous behavior?

2015-07-01 20:30 GMT+02:00 Andrey Kutejko <notifications@github.com>:

**Comment by andy128k** [comment]
I start server with:
```
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4242))
```
And following request returns 400
```
curl -v --cookie "hunchentoot-session=whatever-without-colon" http://localhost:4242/
```

When I run server like this:
```
(ql:quickload '(:clack :hunchentoot))
(clack:clackup #'(lambda (env) '(200 (:content-type "text/plain") ("Hello, Clack!")))
               :server :hunchentoot :port 4242)
```
and send same request there is no answer at all and SB-KERNEL::ARG-COUNT-ERROR is raised.

**Comment by hanshuebner** [comment]
Is this a Clack problem or a Hunchentoot problem? Can it be reproduced with
just Hunchentoot?

2015-07-02 9:28 GMT+02:00 Andrey Kutejko <notifications@github.com>:

**Comment by andy128k** [comment]
Hunchentoot fails on theses lines
https://github.com/edicl/hunchentoot/blob/master/session.lisp#L335-L336

it's also not ok to answer 400 to bad cookies. Server have to discard them.

**Comment by hanshuebner** [comment]
2015-07-02 9:38 GMT+02:00 Andrey Kutejko <notifications@github.com>:

> Hunchentoot fails on theses lines
> https://github.com/edicl/hunchentoot/blob/master/session.lisp#L335-L336
>
> it's also not ok to answer 400 to bad cookies. Server have to discard them.
>
Can you fix the problem, provide references why the changed behavior is
actually correct according to the spec and open a pull request?

Thank you!
-Hans

**Comment by hanshuebner** [comment]
Please confirm that the change that I've just pushed does the right thing.  I decided to use a simpler approach without a regular expression because from a quick review, I could not verify that your regular expression did the right thing.
