### ISSUE TITLE
examples of easy-ssl-acceptor

### ISSUE THREAD

**Issue by muyinliu** [edicl/hunchentoot#108]
Hope there are examples about create server supporting HTTPS.

While `make-instance` of `easy-ssl-acceptor` there are keywords like `:ssl-privatekey-file` `:ssl-certificate-file`, which file should pass? Here is how I generate files with OpenSSL:
```shell
./CA.sh -newca
openssl genrsa -des3 -out server.key 1024
openssl req -new -key server.key -out server.csr
cp server.csr newreq.pem
./CA.sh -sign
cp newcert.pem server.crt
```
After those commands, here is the tree of the directory:
```
.
├── CA.sh
├── demoCA
│   ├── cacert.pem
│   ├── careq.pem
│   ├── certs
│   ├── crl
│   ├── index.txt
│   ├── index.txt.attr
│   ├── index.txt.attr.old
│   ├── index.txt.old
│   ├── newcerts
│   │   ├── BECF060AA4079FB0.pem
│   │   └── BECF060AA4079FB1.pem
│   ├── private
│   │   └── cakey.pem
│   ├── serial
│   └── serial.old
├── newcert.pem
├── newreq.pem
├── server.crt
├── server.csr
└── server.key
```
which file should pass?

**Comment by hanshuebner** [comment]
Please do not attempt to set up an SSL server without first acquiring a basic understanding of SSL, key management and certificates.  Information is readily available on the web, and once you have a basic understanding on how SSL works, the meaning of the arguments will become readily apparent and you won't require any advice.

**Comment by muyinliu** [comment]
```lisp
(defvar *ssl-server* (make-instance 'tbnl:easy-ssl-acceptor 
                                    :port 9443
                                    :ssl-privatekey-file "/Users/muyinliu/ssl/server.key"
                                    :ssl-privatekey-password "password"
                                    :ssl-certificate-file "/Users/muyinliu/ssl/server.crt"))
(hunchentoot:start *ssl-server*)
```
Then request `http://localhost:9443/` in web browser, log:
```
[2015-08-11 17:53:16 [ERROR]] Error while processing connection: A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X00513110) (return code: 1). SSL error queue:
error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
```

**Comment by dwringer** [comment]
Searching for the above error message [A failure in the SSL library occurred . . .] might bring others to this page as it did me, but the reason for it is actually relatively simple: If you start a hunchentoot server using TLS encryption, but then hit it with a browser using "http" rather than "https" in the URL, this error will result.
