### ISSUE TITLE
with-output-to-string stopped working

### ISSUE THREAD

**Issue by patrickmay** [edicl/hunchentoot#111]
I’ve been using Hunchentoot for a couple of years with no problem.  Yesterday some code that had been working stopped working.  An example of the problem is below.

Basically, it seems like with-output-to-string(*standard-output*) no longer results in Hunchentoot writing the result to the client.  I’m using ccl version 1.10-r16196 and the latest Hunchentoot from Quicklisp.  When I run the code below in Slime and then call "curl -G http://127.0.0.1:9876/echo/foo/bar/baz", I can connect to 127.0.0.1:9876, I see the entry in the access log, log-message gets called, but nothing is sent back.

Has something changed in Hunchentoot or have I hosed my environment in some other way?

Thanks,

Patrick

```
(in-package :common-lisp-user)

(ql:quickload :hunchentoot)

(defpackage :org.softwarematters.hunchentoot-issue
  (:nicknames :hunchentoot-issue)
  (:use :common-lisp
        :hunchentoot))

(in-package :hunchentoot-issue)

;;; Define the web server acceptor

(defparameter *test-acceptor*
  (make-instance 'easy-acceptor
                 :port 9876
                 :document-root #p"/Users/Patrick/src/lisp/web/"
                 :access-log-destination "/tmp/issue-access.log"
                 :message-log-destination "/tmp/issue-message.log"))

;;; Utilities
(defconstant +issue-log-file+ #p"/tmp/issue.log")
(defun log-message (message)
  (with-open-file (log +issue-log-file+
                       :direction :output
                       :if-exists :append
                       :if-does-not-exist :create)
    (format log "~A~%" message)))

;;; Define handler

(defun echo-handler ()
  (log-message (request-uri*))
  (with-output-to-string (*standard-output*)
    (request-uri*)))

(setq *dispatch-table*
      (list (create-regex-dispatcher "^/echo/.*" 'echo-handler)))

;;; Start the web server

(start *test-acceptor*)

;(hunchentoot:stop *test-acceptor*)
```

**Comment by hanshuebner** [comment]
Where in your sample ECHO-HANDLER are you writing to *STANDARD-OUTPUT*?

**Comment by patrickmay** [comment]
I'm writing to the *standard-output* stream using with-output-to-string.  This was working two days ago, in a more complex program.  Really.  I'm not crazy!  ;-)

Replacing that with ```(format t "~S" (request-uri*))``` doesn't work, either.  What's the recommended mechanism?

Thanks for the quick reply,

Patrick

**Comment by hanshuebner** [comment]
No, you're not writing to *standard-output* using with-output-to-string.
You are simply using it incorrectly.  You need to return a string from your
handler.  Try a literal string first and then go from there.  Also look at
the documentation of with-output-to-string.

2015-09-22 20:57 GMT+02:00 Patrick <notifications@github.com>:

**Comment by patrickmay** [comment]
I found my root cause in changes to some JSON parsing, but I'm still not sure why it ever worked.

In any case, thanks for the help!
