### ISSUE TITLE
Is it possible to listen on IPv6 interface?

### ISSUE THREAD

**Issue by svetlyak40wt** [edicl/hunchentoot#118]
I have IPv6 only backends and trying to start Hunchentoot on `::0` interface, but receive following error:

```
* (hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4002 :address "::0"))

debugger invoked on a USOCKET:ADDRESS-NOT-AVAILABLE-ERROR in thread
#<THREAD "main thread" RUNNING {1002957423}>:
  Condition USOCKET:ADDRESS-NOT-AVAILABLE-ERROR was signalled.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(USOCKET:SOCKET-LISTEN "::0" 4002 :REUSEADDRESS T :REUSE-ADDRESS NIL :BACKLOG 50 :ELEMENT-TYPE (UNSIGNED-BYTE 8))
```

Is it possible to make Hunchentoot to listen on IPv6 interface?

P.S. – I know, there is [another issue](https://github.com/edicl/hunchentoot/issues/84) about IPv6, but seems it is irrelevant to listening on the socket.

**Comment by svetlyak40wt** [comment]
Seems, nobody else live in the IPv6 only world. Right?

**Comment by stassats** [comment]
```(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4002 :address "::0"))``` works fine here.
