### ISSUE TITLE
Support for something like -DFOREGROUND

### ISSUE THREAD

**Issue by fcbr** [edicl/hunchentoot#121]
I'm looking for a functionality equivalent to Apache's `-DFOREGROUND` command-line option, which keeps Apache from daemonzing.

This will make it easier for Hunchentoot to be used with Docker and sbcl, for example.  I've seen alternatives online where people do a forever `loop` with `sleep` or they try to find the main Hunchentoot listener thread and do a thread-join there, but these all seem a little hackish to me.

**Comment by stassats** [comment]
This can and should be handled by some third party project.
