### ISSUE TITLE
Is it possible to get errors to come up in the debugger?

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [edicl/hunchentoot#125]
When an error happens in Hunchentoot, the server catches and logs the error and keeps going. That's great for production, but horrible for development, since I can't see where the error is coming from! It should be possible to control the catch-and-log behavior so it can be enabled for production, but disabled for development.

**Comment by hanshuebner** [comment]
http://weitz.de/hunchentoot/#*log-lisp-errors-p* and the following section on conditions and error handling should help.
