### ISSUE TITLE
Hunchentoot listener eats CPU on Windows SBCL when idle

### ISSUE THREAD

**Issue by tshatrov** [edicl/hunchentoot#129]
Running a Hunchentoot web app on Windows SBCL will fully consume one core of CPU as of currently. I only noticed this recently when updating quicklisp dist. I narrowed this regression down to this pull request: https://github.com/edicl/hunchentoot/pull/119 .

Before this change Hunchentoot would eat very little CPU when idling. However this change introduces a major performance issue on Windows SBCL. I think it has to do with how `usocket:wait-for-input` works on this combination. Without specifying timeout it enters a tight loop with constant consing.

I tried restoring the timeout argument back to ```+new-connection-wait-time+``` and it solves the issue. I'm not sure however why it was removed in the first place.

**Comment by stassats** [comment]
Well, this will increase the number of wakeups, if usocket:wait-for-input is broken on windows then it should be fixed.

**Comment by stassats** [comment]
Fixed in usocket/usocket#30

**Comment by tshatrov** [comment]
The fix worked, thanks! I was under the wrong impression that usocket's behavior was as expected...
