### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by tomc1998** [edicl/hunchentoot#136]
Hey!

When an error is reported, I want to be able to log the full backtrace and return an error code 500, content-type application/json with some app-protocol specific json data.

This doesn't *seem* possible, but the documentation on errors is fairly lacking so I'm not too sure.

Any way to get this to work?

Thanks.

**Comment by hanshuebner** [comment]
You will need to use an application specific `ACCEPTOR` subclass and implement an `ACCEPTOR-STATUS-MESSAGE` specialized for it.
