### ISSUE TITLE
redirect http=>https on the same port, easy-ssl-acceptor

### ISSUE THREAD

**Issue by erjoalgo** [edicl/hunchentoot#142]
Is it possible to redirect http requests to https on the same port? I'm using easy-ssl-acceptor and haven't found how to do it.

**Comment by lemoinem** [comment]
HTTP and HTTPS protocol are incompatible. You can't run both on the same port.
AFAIK, this is not limited to hunchentoot, but is common to virtually every HTTP server.

You will need to run both on separate ports.
