### ISSUE TITLE
usocket:host-to-hostname

### ISSUE THREAD

**Issue by nneuss** [edicl/hunchentoot#162]
Hi,
having forked the current repository for creating a pull request for another issue I observe that it does not work with current quicklisp.  More precisely in compat.lisp there are now references to USOCKET:HOST-TO-HOSTNAME, but HOST-TO-HOSTNAME is not external in USOCKET.  Using :: works, but is probably not the preferable way to resolve such issues.  What do you propose?
Regards,
Nicolas

**Comment by stassats** [comment]
Works with the current usocket.
