### ISSUE TITLE
HTTP 2 Support

### ISSUE THREAD

**Issue by mateusfccp** [edicl/hunchentoot#166]
Is there any idea of supporting HTTP/2 on Hunchentoot?

**Comment by stassats** [comment]
There are no plans (like there isn't any plans at all for hunchentoot, other than keeping it stable and working).

Can't you use it behind something like nginx to provide HTTP2?

**Comment by mateusfccp** [comment]
> 
> 
> There are no plans (like there isn't any plans at all for hunchentoot, other than keeping it stable and working).
> 
> Can't you use it behind something like nginx to provide HTTP2?

Yes, I can. I just asked because I was willing to do some web with CL but couldn't find any CL http server which provides HTTP/2 support, and hunchentoot is currently the _de facto_ CL http server.

Thanks.
