### ISSUE TITLE
Some javascript files are loaded, others are not loaded

### ISSUE THREAD

**Issue by ulrivo** [edicl/hunchentoot#171]
Hi,

I am doing my first steps with Hunchentoot and have the problem that some javascript file are loaded, others not.

With the following code (which I stripped down to understand the problem) and visiting

    localhost:4242/test-chartist

the network DevTools say that the file chartist.js is *not* loaded, but when visiting 

    localhost:4242/test-vue

the file vue.js ist loaded. 

And I dont understand why chartist.js is not loaded. Any hint, please.

Regards,
Ulrich

    (ql:quickload '(:hunchentoot :cl-who))
    (defpackage test-hunchentoot
      (:use :cl :cl-who :hunchentoot))
    (in-package :test-hunchentoot)

    (start (make-instance 'easy-acceptor :port 4242))

    (define-easy-handler (test-chartist :uri "/test-chartist") ()
      (with-html-output-to-string (s nil :prologue t :indent t)
        (:html
        (:head (:title "Test Chartist"))
        (:body
          (:script :scr "https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js")))))

    (define-easy-handler (test-vue :uri "/test-vue") ()
      (with-html-output-to-string (s nil :prologue t :indent t)
        (:html (:title "Test Vue"))
        (:body
        (:script :src "https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.min.js"))))

**Comment by stassats** [comment]
Try using SRC instead of SCR.
