### ISSUE TITLE
Typo in :reuseaddress in start-listening method?

### ISSUE THREAD

**Issue by szmer** [edicl/hunchentoot#172]
Currently in the `start-listening` method in `acceptor.lisp` the function `usocket:listen` is called with keyword argument `:reuseaddress t`. But according to the current usocket documentation this argument is called `:reuse-address` and the typo argument is ignored (as can be seen in the backtrace in  #118 for example: note `:REUSEADDRESS T :REUSE-ADDRESS NIL`).

This causes me an annoying usocket "address in use" error if I try to redefine a handler in REPL. For now I will be running a locally patched version, but could this be fixed?

**Comment by stassats** [comment]
Usocket accepts both.
