### ISSUE TITLE
define-easy-handler key :host is unknow

### ISSUE THREAD

**Issue by linnilbobo** [edicl/hunchentoot#179]
hi, i  want to make my web site accessible only through my domain name, not directly access the ip address of my vps.so, i try to :
(defun open-site (port)
 (start (setf my-site (make-instance 'easy-acceptor
                                         :port port
                                         :address "xn--btv.xn--io0a7i"
                                         :document-root #p"/home/lin/nil"))))
(open-site 80)
and back #<EASY-ACCEPTOR (host xn--btv.xn--io0a7i, port 80)>
but I can not only see the web page in http://林.网络 
and also can do it with my another domain name  http://www.lin66.win
I can also access it through the IP address   http://173.82.100.130/   
the :address now is not nil , why?

i find another way to set host that is define-easy-handler
so, i try to 
(define-easy-handler (robot :uri "/robots.txt" :host "xn--btv.xn--io0a7i") ( )
  (setf (hunchentoot:content-type*) "text/plain")
   (format nil 
"User-agent: *
Disallow:/
Crawl-delay: 3600
"))
it shows:

debugger invoked on a SB-KERNEL::DEFMACRO-LAMBDA-LIST-BROKEN-KEY-LIST-ERROR in thread
#<THREAD "main thread" RUNNING {1000518083}>:
  Error while parsing arguments to DESTRUCTURING-BIND:
    unknown keyword: :HOST; expected one of :URI, :ACCEPTOR-NAMES, :DEFAULT-PARAMETER-TYPE, :DEFAULT-REQUEST-TYPE
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

there is no problem without key :host
i actually see the host key in source code 
(defmacro define-easy-handler (description lambda-list &body body)
  (name &key uri acceptor-names host
        default-parameter-type default-request-type).
......
at  https://github.com/edicl/hunchentoot/blob/7a904d46246e8490fcdd0699d3a229c3ef334845/easy-handlers.lisp#L170
why it say unknow ?

If I do something wrong, please point out or Tell me the right way
 Please help me, thanks ;)

**Comment by josrr** [comment]
It seems to me that you are running an older version of the code. If you are using emacs, you can visit the code of a function with M-. when the cursor is over its name.

**Comment by linnilbobo** [comment]
after M-.
i see (name &key uri acceptor-names default-parameter-type default-request-type)
there is no host in old version, thanks for your answer

**Comment by linnilbobo** [comment]
the 1.3.0 is great, that my problem has been solved .
i update to it by 
(push #p"/home/lin/hunchentoot-1.3.0" asdf:*central-registry*)
(ql:quickload :hunchentoot)
hunchentoot:*hunchentoot-version*
"1.3.0"
and now, only http://林.网络 can get the "/" page
Through by http://173.82.100.130  will get a 404 page.
it shows: 
Not Found
The requested URL / was not found on this server.
Hunchentoot 1.3.0 (SBCL 2.0.4) at 173.82.100.130 (port 80)

thanks, well down
