### ISSUE TITLE
Error running tests with ECL: "Socket error in "socket": EINVAL (Invalid argument)."

### ISSUE THREAD

**Issue by kat-co** [edicl/hunchentoot#181]
```
;; Starting web server on localhost:4241.An error occurred during initialization:
Socket error in "socket": EINVAL (Invalid argument).
```

v1.3.0 built using Guix.

**Comment by stassats** [comment]
Works here. You probably don't have /etc/protocols

**Comment by kat-co** [comment]
This works on SBCL under the same build environment. The build chroot-jail would prevent the build reaching out to `/etc/protocols`, but why would it be different between SBCL and ECL?

**Comment by stassats** [comment]
It works on SBCL because of https://github.com/sbcl/sbcl/commit/34eab1610a5756ebf383303eccadaf829d04f92b

**Comment by kat-co** [comment]
Ah! Thank you very much for linking that patch.
