### ISSUE TITLE
Stuck on a rasbery pi the web server don't start 

### ISSUE THREAD

**Issue by yodatak** [edicl/hunchentoot#184]
Hi im following this tutorial 
To reproduce the issue:
```common-lisp
sbcl
(ql:quickload '("hunchentoot" "caveman" "spinneret" "djula"))
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4002 :address nil))
```
and i found a issue on my raspberry pi on rasbian i never get the prompt back 
When i try this on a fresh debian 10 vagrant on x64 its works.

Is this a issue on network resolution or something ?

https://lisp-journey.gitlab.io/blog/web-development-in-common-lisp/#simple-webserver

**Comment by mdbergmann** [comment]
I think that SBCL doesn't have thread support on raspberry pi (rasperian), in which case the `(hunchentoot:start` will block.
You should maybe check for ECL instead.

**Comment by stassats** [comment]
But does the server still work? And you need the 64-bit sbcl variant to get threads.

**Comment by vindarel** [comment]
Yes the server still works.

@mdbergmann In our case CCL made it beautifuly (easy to install and very fast to compile).
