### ISSUE TITLE
The function USOCKET::FDSET-ALLOC is undefined. 

### ISSUE THREAD

**Issue by silent-entertainment** [edicl/hunchentoot#187]
I'm trying to get an http server running on CL REPL for Android, and I'm having difficulty.

CL REPL is up to date, from Play Store.

I installed quicklisp via CL REPL, and it seems to be working.

I tried hunchentoot and hunchentoot-test. For hunchentoot, after starting the service with

(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4242))

 the REPL drops into the debugger, only saying, "Top level in: #<process hunchentoot-listener-*:4242 0xb60ed5c0>." This seems to indicate that it's running, but Firefox can't connect at 127.0.0.1:4242 per the hunchentoot documentation. I also tried going to localhost:4242, with three same result.

After exiting the debugger, the output says,

"
CONDITION OF TYPE: UNKNOWN-ERROR
The condition The function USOCKET::FDSET-ALLOC is undefined. occurred with errno 0.
"

I installed USOCKET, but I'm still seeing the same error. 

hunchentoot-test didn't show any errors, but Firefox can't connect.

I do have some experience with hunchentoot on a Linux box, years ago.

Before attempting the installation I did try to research ECL and EQL5 feature implementations and missing features, and I looked for reports from anyone who successfully ran an http server on CL ECL for Android. Other than the ECL documentation about threads, I found zero information.

Are there any known related issues?

**Comment by stassats** [comment]
That's a question for usocket.
