### ISSUE TITLE
Docs mismatch

### ISSUE THREAD

**Issue by nhabedi** [edicl/hunchentoot#192]
I just checked http://edicl.github.io/hunchentoot/ because someone mailed me a question and I _think_ the documentation part of the following commit was somehow lost when 1.3.0 was released:

https://github.com/edicl/hunchentoot/commit/585b45b6b873f2da421fdf456b61860ab5868207

**Comment by enometh** [comment]
The documentation states
```
By default, Hunchentoot serves the files from the www/ directory in its source tree. In the distribution, that directory contains a HTML version of the documentation as well as the error templates.
```
The default error templates used to default to files under www/errors/404.html etc. which got removed in this commit. they still default to the same values but they
are no longer found there.
