### ISSUE TITLE
How do I make hunchentoot refresh the static files?

### ISSUE THREAD

**Issue by theamazingwaffle** [edicl/hunchentoot#203]
I have created an `easy-acceptor` and set a `:document-root` but when i change the statically served files, hunchentoot doesn't see the change and still serves the old thing, until i stop the acceptor and create a new one.

Edit: Actually, it seems like it refreshes the files automatically after a certain time. Can I make this interval smaller?

**Comment by stassats** [comment]
Are you sure it's not just cached by the browser?

**Comment by theamazingwaffle** [comment]
I am sorry, indeed it was caching.
