### ISSUE TITLE
hunchentoot:handle-static-file

### ISSUE THREAD

**Issue by juan-reynoso** [edicl/hunchentoot#209]
Hello everybody.

Hunchentoot shows me the following error some times, I do not how to reproduce the error.

All the files are in the rigth path in other words the files exist.

```
Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>:
  Broken pipe
   [Condition of type SB-INT:BROKEN-PIPE]

Restarts:
 0: [ABORT] abort thread (#<THREAD "hunchentoot-worker-127.0.0.1:48390" RUNNING {100181C5B3}>)

Backtrace:
  0: (SB-IMPL::FINISH-WRITING-SEQUENCE #(137 80 78 71 13 10 ...) #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}> 0 8192)
      Locals:
        END = 8192
        SEQUENCE = #(137 80 78 71 13 10 ...)
        START = 0
        STREAM = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
  1: (SB-IMPL::BUFFER-OUTPUT #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}> #(137 80 78 71 13 10 ...) 0 8192)
      Locals:
        END = 8192
        START = 0
        STREAM = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
        THING = #(137 80 78 71 13 10 ...)
  2: (SB-IMPL::WRITE-SEQ-IMPL #(137 80 78 71 13 10 ...) #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}> 0 8192)
      Locals:
        %END = 8192
        SEQ = #(137 80 78 71 13 10 ...)
        START = 0
        STREAM = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
  3: (WRITE-SEQUENCE #(137 80 78 71 13 10 ...) #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}> :START 0 :END 8192)
      Locals:
        #:.DEFAULTING-TEMP. = 0
        #:.DEFAULTING-TEMP.#1 = 8192
        SB-IMPL::SEQ = #(137 80 78 71 13 10 ...)
        STREAM = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
  4: (HUNCHENTOOT:HANDLE-STATIC-FILE #P"/home/my-user/src/lisp/huuii/wwwroot/img/traders.png" "image/png" NIL)
      Locals:
        BUF = #(137 80 78 71 13 10 ...)
        BYTES-TO-SEND = 43798
        CALLBACK = NIL
        CONTENT-TYPE = "image/png"
        FILE = #<SB-SYS:FD-STREAM for "file /home/my-user/src/lisp/huuii/wwwroot/img/traders.png" {10040869D3}>
        OUT = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
        PATHNAME = #P"/home/my-user/src/lisp/huuii/wwwroot/img/traders.png"
  5: ((:METHOD HUNCHENTOOT:HANDLE-REQUEST (HUNCHENTOOT:ACCEPTOR HUNCHENTOOT:REQUEST)) #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)> #<HUNCHENTOOT:REQUEST {1004083293}>) [fast-method]
      Locals:
        SB-C::.ANONYMOUS. = #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)>
        SB-C::.ANONYMOUS.#1 = #<HUNCHENTOOT:REQUEST {1004083293}>
  6: ((:METHOD HUNCHENTOOT:PROCESS-REQUEST (T)) #<HUNCHENTOOT:REQUEST {1004083293}>) [fast-method]
      Locals:
        SB-C::.ANONYMOUS. = #<HUNCHENTOOT:REQUEST {1004083293}>
      Catch-tags:
        HUNCHENTOOT::HANDLER-DONE
        HUNCHENTOOT::REQUEST-PROCESSED
  7: (HUNCHENTOOT::DO-WITH-ACCEPTOR-REQUEST-COUNT-INCREMENTED #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)> #<FUNCTION (LAMBDA NIL :IN HUNCHENTOOT:PROCESS-CONNECTION) {100408315B}>)
      Locals:
        SB-C::.ANONYMOUS. = #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)>
        FUNCTION = #<FUNCTION (LAMBDA () :IN HUNCHENTOOT:PROCESS-CONNECTION) {100408315B}>
  8: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)> #<USOCKET:STREAM-USOCKET {100181C013}>) [fast-method]
      Locals:
        SB-C::.ANONYMOUS. = #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)>
        HUNCHENTOOT::LOCAL = ("127.0.0.1" 8003)
        HUNCHENTOOT::REMOTE = ("127.0.0.1" 48390)
        HUNCHENTOOT::SOCKET = #<USOCKET:STREAM-USOCKET {100181C013}>
        HUNCHENTOOT::SOCKET-STREAM = #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:48390" {100181BEB3}>
  9: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)> #<USOCKET:STREAM-USOCKET {100181C013}>) [fast-method]
      Locals:
        SB-C::.ANONYMOUS. = #<HUNCHENTOOT:EASY-ACCEPTOR (host 0.0.0.0, port 8003)>
        SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL :FUNCTION #<FUNCTION (SB-PCL::FAST-METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T))> :PV NIL :NEXT-METHOD-CALL NIL :ARG-INFO (2))
        HUNCHENTOOT::SOCKET = #<USOCKET:STREAM-USOCKET {100181C013}>
 10: ((:METHOD HUNCHENTOOT::HANDLE-INCOMING-CONNECTION% (HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER T)) #<HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER {1005BC6153}> #<USOCKET:STREAM-USOCKET {1001..
      Locals:
        HUNCHENTOOT::SOCKET = #<USOCKET:STREAM-USOCKET {100181C013}>
        HUNCHENTOOT:TASKMASTER = #<HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER {1005BC6153}>
 11: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 12: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 13: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
 14: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
 16: (SB-THREAD::RUN)
 17: ("foreign function: call_into_lisp_")
 18: ("foreign function: funcall1")

```

The error  could be with any file like css, png, js etc.
e.g.
(HUNCHENTOOT:HANDLE-STATIC-FILE #P"/home/my-user/src/lisp/huuii/wwwroot/fonts/Quicksand/Quicksand-Regular.ttf" NIL NIL)
(HUNCHENTOOT:HANDLE-STATIC-FILE #P"/home/my-user/src/lisp/huuii/wwwroot/img/traders.png" "image/png" NIL)

In order to dispatch the directories like css,js, images etc. I have the following code:
e.g.
```
;; Dispatcher for stylesheets
(push (create-folder-dispatcher-and-handler "/css/"
					    (concatenate 'string *wwwroot*
							 "/css/"))
      *dispatch-table*)

```

I have sbcl version
SBCL 2.2.9.14-5ae582603

Hunchentoot with the last commit
ef175853ce4e2f6b3c7f5927450d8e8c44e70a4c

Usocket with the last commit
bc60675f619b9318251a95f8a6d6bf374327b07b

**Comment by phoe** [comment]
A broken pipe error means that the remote end has disconnected before the sequence (in this case, the file being uploaded to the client) was fully written to the network stream.

Normally I'd handle this condition via `#'abort`, but I don't know what's the best way of telling Hunchentoot to execute its worker threads in a custom dynamic context - probably by defining a custom acceptor subclass, defining a custom `:around` method on `process-connection` that does `(handler-bind ((sb-int:broken-pipe #'abort)) (call-next-method))`, and then using this custom acceptor class in Hunchentoot.

But yes, maybe this should be handled in Hunchentoot in some way rather than deferring to the users? A broken pipe sounds like something that a HTTP server should be able to deal with on its own.

**Comment by juan-reynoso** [comment]
Thanks so much for the information.

**Comment by juan-reynoso** [comment]
A workaround
I have modified handle-static-file function
I added  handler-case

(defun handle-static-file (pathname &optional content-type callback)
  "A function which acts like a Hunchentoot handler for the file
denoted by PATHNAME.  Sends a content type header corresponding to
CONTENT-TYPE or \(if that is NIL) tries to determine the content type
via the suffix of the file.
CALLBACK is run just before sending the file, and can be used
to set headers or check authorization;
arguments are the filename and the (guessed) content-type."
  (when (or (wild-pathname-p pathname)
            (not (fad:file-exists-p pathname))
            (fad:directory-exists-p pathname))
    ;; file does not exist
    (setf (return-code*) +http-not-found+)
    (abort-request-handler))
  (unless content-type
    (setf content-type (mime-type pathname)))
  (let ((time (or (file-write-date pathname)
                  (get-universal-time)))
        bytes-to-send)
    (setf (content-type*) (or (and content-type
                                   (maybe-add-charset-to-content-type-header content-type (reply-external-format*)))
                              "application/octet-stream")
          (header-out :last-modified) (rfc-1123-date time)
          (header-out :accept-ranges) "bytes")
    (handle-if-modified-since time)
    (unless (null callback)
      (funcall callback pathname content-type))
    (with-open-file (file pathname
                          :direction :input
                          :element-type 'octet)
      (setf bytes-to-send (maybe-handle-range-header file)
            (content-length*) bytes-to-send)
      (let ((out (send-headers))
            (buf (make-array +buffer-length+ :element-type 'octet)))
	(handler-case
	    (progn
	      (loop
		(when (zerop bytes-to-send)
		  (return))
		(let* ((chunk-size (min +buffer-length+ bytes-to-send)))
		  (unless (eql chunk-size (read-sequence buf file :end chunk-size))
		    (error "can't read from input file"))
		  (write-sequence buf out :end chunk-size)
		  (decf bytes-to-send chunk-size)))
              (finish-output out))
	  ;; catches the error
	  (error  (err)
            ;; display information about the file and the error
	    (format t "~%~% -- Error information: -- ~% ~%")
	    (format t "~% pathname ~a" pathname)
	    (format t "~% file ~a" file)
	    (format t "~% ~% the error: ~a ~%" err)
             ;; finally abort
	    (abort )))))))

`Logs`

 -- Error information: -- 
 

 pathname /home/my-user/src/lisp/huuii/wwwroot/fonts/Open_Sans/OpenSans-Semibold.ttf
 file #<FD-STREAM for "file /home/my-user/src/lisp/huuii/wwwroot/fonts/Open_Sans/OpenSans-Semibold.ttf" {1003C6B793}>
 
 the error: Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:8003, peer: 127.0.0.1:51078" {100391FEC3}>:
              Broken pipe
