### ISSUE TITLE
docs reference clbuild

### ISSUE THREAD

**Issue by cgay** [edicl/hunchentoot#229]
The docs say "Hunchentoot and its dependencies can also be installed with [clbuild](http://common-lisp.net/project/clbuild/)", but clbuild appears to be defunct. Or at least clbuild.common-lisp.dev links to gitorious.org, which definitely appears to be dead.  Is clbuild still a valid way to build Hunchentoot?  (I'm just getting back into the CL ecosystem after many years and it can be challenging to figure out what's current.)

**Comment by cgay** [comment]
Just going to add similar trivial stuff here...

Dead links:
* http://yaws.hyber.org/privbind.yaws
* https://mailman.red-bean.com/pipermail/lispweb/2006-October/001342.html
* http://weitz.de/patches.html seems to redirect to lisp.html and it's not clear why one should read lisp.html before submitting patches.

The example code to run `hunchentoot-test` dies:

```CL-USER> (asdf:oos 'asdf:load-op :hunchentoot-test)
WARNING: System definition file #P"/Users/cgay/lisp/quicklisp/dists/quicklisp/software/hunchentoot-v1.3.0/hunchentoot.asd" contains definition for system "hunchentoot-test". Please only define "hunchentoot" and secondary systems with a name starting with "hunchentoot/" (e.g. "hunchentoot/test") in that file.
WARNING: System definition file #P"/Users/cgay/lisp/quicklisp/dists/quicklisp/software/hunchentoot-v1.3.0/hunchentoot.asd" contains definition for system "hunchentoot-dev". Please only define "hunchentoot" and secondary systems with a name starting with "hunchentoot/" (e.g. "hunchentoot/test") in that file.
; Evaluation aborted on Component :CL-WHO not found, required by #<SYSTEM "hunchentoot-test">.
```

You do mention further up that `cl-who` and `drakma` are requirements for the tests. Perhaps move that note down to just before suggesting to run `(asdf:oos 'asdf:load-op :hunchentoot-test)`.

**Comment by hanshuebner** [comment]
Carl, welcome back!

clbuild is definitely dead and needs to be removed from the documentation.
Quicklisp should be used instead, and it would probably make sense to
suggest using that for running the tests (and loading the dependencies).
The ASDF warnings are from a refactoring that was made to ASDF to which
Stas and I tried to oppose, but failed.  It should not be too hard to fix
by moving :hunchentoot-test to a separate .asd file.  Do you have time to
send a PR?

Am Fr., 26. Apr. 2024 um 06:46 Uhr schrieb Carl Gay <
***@***.***>:

**Comment by cgay** [comment]
Thanks. :) If I end up using hunchentoot I'll definitely send PRs, but for now I'm just getting the lay of the land.
