### ISSUE TITLE
Drop single-threaded-implementation support?

### ISSUE THREAD

**Issue by kilianmh** [edicl/hunchentoot#231]
- Bordeaux-Threads does not load at all on single threaded implementations since June 2022. See [39d6790](https://github.com/sionescu/bordeaux-threads/commit/39d6790d24002df43e24b3c2d6f41524839b74d5). 
- Hunchentoot requires bordeaux-threads by default

-> Should all code related to single-threads (e.g. taskmasker) be removed?

**Comment by stassats** [comment]
You should still be able to run in single-threaded mode even if the implementation has threads.
