### ISSUE TITLE
URL "/static/%s" returns 500 instead of 4xx

### ISSUE THREAD

**Issue by phmarek** [edicl/hunchentoot#85]
Invalid URLs with non-hex characters after the `%` return an internal-server-error (500) instead of a proper `400 Bad Request` result.

**Comment by stassats** [comment]
That's because it causes an error.

**Comment by hanshuebner** [comment]
I think the point is that instead of assuming responsibility for the error
on its own end by the way of a 5xx, Hunchentoot should tell the client that
it made send an unsyntactic request by the way of a 4xx status code.

**Comment by stassats** [comment]
The error would have to be solved first.

**Comment by hanshuebner** [comment]
The error is to call parse-integer on the unvalidated string, so the fix
would be to validate it before parsing it and generate a 4xx response if
the two characters following the % are not valid hex digits.  Or do I
misunderstand?

2015-01-23 17:49 GMT+01:00 Stas Boukarev <notifications@github.com>:

**Comment by stassats** [comment]
Something like that.
