### ISSUE TITLE
Session implementation is lacking

### ISSUE THREAD

**Issue by Ralt** [edicl/hunchentoot#87]
Hi,

After some quick testing, I've found that, in my humble opinion, hunchentoot sessions are lacking some (from today's standards) necessary features.

- The session cookie should be HttpOnly (more about that here: https://www.owasp.org/index.php/HttpOnly)
- Using `remove-session` should send a `Set-Cookie` header to remove the session cookie (e.g. `Set-Cookie: hunchentoot-session=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`)

I understand that these are "breaking changes". I wonder if you'd still be interested in accepting these features. I think I could send you a pull request if you'd like so.

Cheers,
Florian

**Comment by hanshuebner** [comment]
I think these suggestions are prudent and a patch would be welcome.

2015-03-06 2:21 GMT+01:00 Florian Margaine <notifications@github.com>:

**Comment by Ralt** [comment]
Thanks for merging!
