### ISSUE TITLE
Add session-regenerate-id

### ISSUE THREAD

**Issue by Ralt** [edicl/hunchentoot#95]
Hi,

Such a method would just regenerate the session id without changing anything else in the data held by the session.

This method helps to prevent against [session fixation attacks](https://www.owasp.org/index.php/Session_fixation). It should be called when logging a user if a session already exists. This, of course, should be done by the application using hunchentoot.

Would you agree to add this method to hunchentoot?

If you need a patch, I'm willing to open a PR.

Cheers,
Florian

**Comment by hanshuebner** [comment]
I'm open to adding this feature.  Please remember to include documentation
in your PR.

Thanks! Hans

2015-05-02 3:00 GMT+02:00 Florian Margaine <notifications@github.com>:

**Comment by Ralt** [comment]
Merged in #96
