### ISSUE TITLE
Invalid program: Can't bind or assign to constant SECOND.

### ISSUE THREAD

**Issue by renzo-orsini** [edicl/hunchentoot#99]
I have a relatively small hunchentoot web application that worked on mac os x yosemite and linux, and that now does not work on linux any more, maybe due to recent update to all quicklisp packages. The application still works without any problem in mac os x. I use CCL both on mac and linux. 

This is the  backtrace obtained with slime (after disabling error reporting by hunchentoot, otherwise nothing is printed on the log):

The log is given in the following gist, since it not visible if I paste it: https://gist.github.com/renzo-orsini/2ce407b383c25566466f

**Comment by stassats** [comment]
Some code did (defconstant second something), this is not related to hunchentoot
